Dump a native stack with gdb after four minutes

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,5 +1,18 @@
 #!/bin/bash
 
+function waitAndDump {
+  # About four minutes
+  sleep 240
+
+  local NODE_PID=$(cat mocha.pid)
+  if [ -z "${NODE_PID}" ]; then
+    echo "Unable to read node pid from mocha.pid"
+    exit 1
+  fi
+
+  gdb -batch -ex "thread apply all bt" -p ${NODE_PID}
+}
+
 function updateStatus {
   STATUS=$1
   CTX=$2
@@ -168,6 +181,7 @@ function runTests {
   if [ $LINT_RESULT -ne 0 ]; then echo ">>> LINTING FAILED! <<< Continuing on to tests..."; fi
 
   echo "Running specs..."
+  waitAndDump &
   "$ATOM_SCRIPT_PATH" --test test
   TEST_RESULT=$?
 
